# Generated by Django 5.2.3 on 2025-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='category',
            field=models.CharField(choices=[('exception', 'Exception/Error'), ('performance', 'Performance Issue'), ('security', 'Security Event'), ('data_quality', 'Data Quality Issue'), ('integration', 'External Integration'), ('resource', 'Resource Issue'), ('configuration', 'Configuration Issue'), ('test_failure', 'Test Failure'), ('user_feedback', 'User Feedback')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='source',
            field=models.CharField(choices=[('django_error', 'Django Error Handler'), ('middleware', 'Error Middleware'), ('log_parser', 'Log File Parser'), ('performance', 'Performance Monitor'), ('ai_system', 'AI System'), ('test_runner', 'Test Runner'), ('cache', 'Cache System'), ('database', 'Database'), ('api', 'API Endpoint'), ('background_task', 'Background Task'), ('user_report', 'User Report'), ('site_feedback', 'Site Feedback'), ('health_check', 'Health Check')], db_index=True, max_length=50),
        ),
    ]
