# Generated by Django 5.2.3 on 2025-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
