# Generated by Django 4.2.23 on 2025-07-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0007_alter_counciltype_options_councillist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "formula",
                    models.CharField(
                        help_text="Fields to sum, e.g. 'total_debt+current_liabilities'",
                        max_length=255,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("duration", models.PositiveIntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name="CouncilCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="council_finance.council",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="council_finance.counterdefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("council", "counter")},
            },
        ),
    ]
