# Generated by Django 5.2.4 on 2025-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0008_counter_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterdefinition",
            name="friendly_format",
            field=models.BooleanField(
                default=False, help_text="Use short forms e.g. £1m"
            ),
        ),
        migrations.AddField(
            model_name="counterdefinition",
            name="precision",
            field=models.PositiveIntegerField(
                default=0, help_text="Decimal places to display"
            ),
        ),
        migrations.AddField(
            model_name="counterdefinition",
            name="show_currency",
            field=models.BooleanField(
                default=True, help_text="Prefix with £ and include comma separators"
            ),
        ),
    ]
