# Generated by Django 5.2.4 on 2025-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0010_sanitise_figure_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="figuresubmission",
            name="needs_populating",
            field=models.BooleanField(
                default=False,
                help_text="True if the source dataset did not provide this value",
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps
            .get_model("council_finance", "FigureSubmission")
            .objects.filter(models.Q(value__isnull=True) | models.Q(value=""))
            .update(needs_populating=True),
            migrations.RunPython.noop,
        ),
    ]
