# Generated by Django 5.2.3 on 2025-07-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0013_alter_datafield_category_and_more'),
        ('council_finance', '0014_update_field_defs'),
    ]

    operations = [
    ]
