# Generated by Django 5.2.4 on 2025-07-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0016_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterdefinition",
            name="default_for_detail",
            field=models.BooleanField(
                default=False, help_text="Show by default on the council detail page"
            ),
        ),
        migrations.AlterField(
            model_name="datafield",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("monetary", "Monetary"),
                    ("integer", "Integer"),
                    ("text", "Text"),
                    ("url", "URL"),
                    ("list", "List"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datafield",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
