# Generated by Django 5.2.4 on 2025-07-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0016_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterdefinition",
            name="show_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Show on council pages unless disabled for a specific council",
            ),
        ),
    ]
