# Generated by Django 5.2.4 on 2025-07-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0022_ip_and_blocklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rejectionlog",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="council_finance.datafield",
            ),
        ),
        migrations.AlterField(
            model_name="rejectionlog",
            name="reason",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("data_incorrect", "The data wasn't correct"),
                    ("no_sources", "We can't find reliable sources"),
                    ("invalid_field", "Invalid field"),
                    ("other", "Other"),
                ],
            ),
        ),
    ]
