# Generated by Django 5.2.3 on 2025-07-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0023_invalid_field_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rejectionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
