# Generated by Django 4.2.23 on 2025-07-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0025_council_website_protected"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterdefinition",
            name="headline",
            field=models.BooleanField(
                default=False, help_text="Highlight this counter as a headline figure"
            ),
        ),
        migrations.AddField(
            model_name="datafield",
            name="council_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Council types this field applies to",
                to="council_finance.counciltype",
            ),
        ),
    ]
