# Generated by Django 5.2.4 on 2025-07-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0026_counterdefinition_headline_datafield_council_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouncilCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Council capability",
                "verbose_name_plural": "Council capabilities",
            },
        ),
        migrations.AddField(
            model_name="counterdefinition",
            name="council_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Council types this counter applies to",
                to="council_finance.counciltype",
            ),
        ),
        migrations.AddField(
            model_name="counciltype",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Functions this type of council performs",
                to="council_finance.councilcapability",
            ),
        ),
    ]
