# Generated by Django 5.2.4 on 2025-07-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0028_site_and_group_counters"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupcounter",
            name="year",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit to a single year or leave blank to sum all years",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="council_finance.financialyear",
            ),
        ),
        migrations.AddField(
            model_name="sitecounter",
            name="year",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit to a single year or leave blank to sum all years",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="council_finance.financialyear",
            ),
        ),
    ]
