# Generated by Django 5.2.4 on 2025-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0029_add_counter_year_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecounter",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Optional description shown via info icon on the home page",
            ),
        ),
    ]
