# Generated by Django 5.2.4 on 2025-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0031_sitecounter_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factoid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "factoid_type",
                    models.CharField(
                        choices=[
                            ("percent_change", "Percentage change on last year"),
                            ("highest", "Highest council"),
                            ("lowest", "Lowest council"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "counters",
                    models.ManyToManyField(
                        blank=True, to="council_finance.counterdefinition"
                    ),
                ),
                (
                    "group_counters",
                    models.ManyToManyField(
                        blank=True, to="council_finance.groupcounter"
                    ),
                ),
                (
                    "site_counters",
                    models.ManyToManyField(
                        blank=True, to="council_finance.sitecounter"
                    ),
                ),
            ],
        ),
    ]
