# Generated by Django 4.2.8 on 2025-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0035_following_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="latest_population",
            field=models.IntegerField(
                blank=True,
                help_text="Latest population figure across all years",
                null=True,
            ),
        ),
    ]
