# Generated by Django 5.2.4 on 2025-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council_finance", "0042_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="request",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
