# Generated by Django 5.2.3 on 2025-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0044_activity_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(choices=[('auto', 'Auto (follows system)'), ('light', 'Light theme'), ('dark', 'Dark theme'), ('high-contrast', 'High contrast')], default='auto', help_text='Choose your preferred color theme', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small (14px)'), ('medium', 'Medium (16px)'), ('large', 'Large (18px)'), ('extra-large', 'Extra Large (20px)')], default='medium', help_text='Choose your preferred font size for better readability', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_contrast_mode',
            field=models.BooleanField(default=False, help_text='Enable high contrast colors for better visibility'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='category',
            field=models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow'), ('income', 'Income'), ('spending', 'Spending'), ('general', 'General'), ('characteristic', 'Characteristics'), ('calculated', 'Calculated')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataissue',
            name='issue_type',
            field=models.CharField(choices=[('missing', 'Missing'), ('suspicious', 'Suspicious')], max_length=20),
        ),
    ]
