# Generated by Django 5.2.3 on 2025-07-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0045_userprofile_color_theme_userprofile_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed/Disbanded'), ('merged', 'Merged'), ('renamed', 'Renamed')], default='active', help_text='Current status of the council', max_length=20),
        ),
    ]
