# Generated by Django 5.2.3 on 2025-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0046_add_council_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialyear',
            options={'ordering': ['-label']},
        ),
        migrations.AddField(
            model_name='financialyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Mark as current financial year'),
        ),
    ]
