# Generated by Django 5.2.3 on 2025-07-14 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('council_finance', '0047_add_financial_year_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='council',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('merge', 'Merge'), ('import', 'Import'), ('export', 'Export'), ('auth', 'Authentication'), ('system', 'System'), ('moderation', 'Moderation'), ('contribution', 'Contribution'), ('council_merge', 'Council Merge'), ('financial_year', 'Financial Year Management'), ('data_correction', 'Data Correction'), ('bulk_operation', 'Bulk Operation')], default='system', help_text='Type of activity performed', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.CharField(default='Legacy activity', help_text='Human-readable description of the activity', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured data about the activity'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_council',
            field=models.ForeignKey(blank=True, help_text='Council this activity relates to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='council_finance.council'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', help_text='Status of the activity', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created'], name='council_fin_user_id_6d3f18_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['related_council', '-created'], name='council_fin_related_915c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', '-created'], name='council_fin_activit_c36e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['status', '-created'], name='council_fin_status_4a4279_idx'),
        ),
    ]
