# Generated by Django 5.2.3 on 2025-07-14 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0048_enhance_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('current_value', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied to Data')], default='pending', max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_description', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions_v2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_v2', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council_finance.financialyear')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', 'created'], name='council_fin_status_059b53_idx'), models.Index(fields=['council', 'field'], name='council_fin_council_764b5a_idx'), models.Index(fields=['user', 'status'], name='council_fin_user_id_646600_idx'), models.Index(fields=['field', 'status'], name='council_fin_field_i_b707a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouncilCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['council', 'field'], name='council_fin_council_037798_idx'), models.Index(fields=['field'], name='council_fin_field_i_38b74a_idx')],
                'unique_together': {('council', 'field')},
            },
        ),
        migrations.CreateModel(
            name='CouncilCharacteristicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('import', 'Data Import'), ('contribution', 'User Contribution'), ('admin', 'Admin Edit'), ('api', 'API Update')], default='contribution', max_length=50)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_history', to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['council', 'field', 'changed_at'], name='council_fin_council_e02b68_idx'), models.Index(fields=['changed_at'], name='council_fin_changed_d07f43_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('is_provisional', models.BooleanField(default=False)),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source_document', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_figures', to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.financialyear')),
            ],
            options={
                'indexes': [models.Index(fields=['council', 'field', 'year'], name='council_fin_council_590c5b_idx'), models.Index(fields=['year', 'field'], name='council_fin_year_id_48d97a_idx'), models.Index(fields=['council', 'year'], name='council_fin_council_24f8a6_idx')],
                'unique_together': {('council', 'field', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FinancialFigureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('import', 'Data Import'), ('contribution', 'User Contribution'), ('admin', 'Admin Edit'), ('correction', 'Data Correction'), ('audit', 'Audit Adjustment')], default='contribution', max_length=50)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.financialyear')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['council', 'field', 'year', 'changed_at'], name='council_fin_council_78b60a_idx'), models.Index(fields=['changed_at'], name='council_fin_changed_bcd3ee_idx')],
            },
        ),
    ]
