# Generated by Django 5.2.3 on 2025-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0050_financialyear_end_date_financialyear_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='is_forecast',
            field=models.BooleanField(default=False, help_text='True if this is a future year with projected/estimated figures'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='is_provisional',
            field=models.BooleanField(default=True, help_text="True if this year's figures are still being collected/finalized"),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this financial year (data quality, issues, etc.)'),
        ),
    ]
