# Generated by Django 5.2.3 on 2025-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0026_fix_list_fields'),
        ('council_finance', '0051_financialyear_is_forecast_and_more'),
    ]

    operations = [
    ]
