# Generated by Django 5.2.3 on 2025-07-17 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('council_finance', '0054_enhanced_following_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('flag_type', models.CharField(choices=[('content_incorrect', 'Data is Incorrect'), ('content_outdated', 'Data is Outdated'), ('content_spam', 'Spam or Irrelevant'), ('content_duplicate', 'Duplicate Entry'), ('user_abuse', 'User Abuse/Harassment'), ('user_spam', 'User Spamming'), ('system_error', 'System/Technical Error'), ('other', 'Other (See Description)')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flags', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_raised', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlagComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='council_finance.flag')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total_flags', models.PositiveIntegerField(default=0)),
                ('unique_flaggers', models.PositiveIntegerField(default=0)),
                ('first_flagged', models.DateTimeField(auto_now_add=True)),
                ('last_flagged', models.DateTimeField(auto_now=True)),
                ('is_under_review', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('auto_escalated', models.BooleanField(default=False)),
                ('escalation_threshold', models.PositiveIntegerField(default=3)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-last_flagged'],
            },
        ),
        migrations.CreateModel(
            name='UserModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warning', 'Warning'), ('temp_ban', 'Temporary Ban'), ('perm_ban', 'Permanent Ban'), ('flag_limit', 'Flag Submission Limit'), ('contrib_limit', 'Contribution Limit'), ('restored', 'Privileges Restored')], max_length=15)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='council_finance.flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['status', '-created_at'], name='council_fin_status_fe13a1_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['content_type', 'object_id'], name='council_fin_content_9b3f46_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['flagged_by', '-created_at'], name='council_fin_flagged_b2082d_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['priority', 'status'], name='council_fin_priorit_b849d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('flagged_by', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='council_fin_content_9df6db_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['total_flags', '-last_flagged'], name='council_fin_total_f_e4a693_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedcontent',
            index=models.Index(fields=['is_under_review', 'is_resolved'], name='council_fin_is_unde_c417f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flaggedcontent',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='usermoderationrecord',
            index=models.Index(fields=['user', '-created_at'], name='council_fin_user_id_0c3d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoderationrecord',
            index=models.Index(fields=['action', 'expires_at'], name='council_fin_action_2c7e7a_idx'),
        ),
    ]
