# Generated by Django 5.2.3 on 2025-07-18 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0055_flag_flagcomment_flaggedcontent_usermoderationrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('confidence_level', models.CharField(choices=[('high', 'High - Official source'), ('medium', 'Medium - Reliable source'), ('low', 'Low - Unverified')], default='medium', max_length=20)),
                ('source_type', models.CharField(choices=[('official', 'Official council data'), ('government', 'Government dataset'), ('community', 'Community contribution'), ('calculated', 'Calculated value')], default='community', max_length=20)),
                ('source_notes', models.TextField(blank=True, help_text='Notes about the source of this data')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.council')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('year', models.ForeignKey(blank=True, help_text="Leave blank for characteristics that don't vary by year", null=True, on_delete=django.db.models.deletion.CASCADE, to='council_finance.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='DataApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.CharField(blank=True, help_text='Previous value before this update', max_length=255)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes about why this data was approved')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('council_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.councildata')),
                ('source_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='council_finance.figuresubmission')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='councildata',
            index=models.Index(fields=['council', 'field'], name='council_fin_council_af7c05_idx'),
        ),
        migrations.AddIndex(
            model_name='councildata',
            index=models.Index(fields=['council', 'year'], name='council_fin_council_b28742_idx'),
        ),
        migrations.AddIndex(
            model_name='councildata',
            index=models.Index(fields=['field', 'year'], name='council_fin_field_i_d9f31e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='councildata',
            unique_together={('council', 'year', 'field')},
        ),
    ]
