# Generated by Django 5.2.3 on 2025-07-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0058_add_ai_analysis_models'),
    ]

    operations = [
    ]
