# Generated by Django 5.2.3 on 2025-07-22 17:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0059_enhance_email_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingprofilechange',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='change_type',
            field=models.CharField(choices=[('email', 'Email Address'), ('password', 'Password'), ('profile', 'Profile Information'), ('security', 'Security Settings')], default='profile', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='field',
            field=models.CharField(default='unknown', help_text='Field being changed', max_length=50),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='new_value',
            field=models.TextField(default='', help_text='New value to be applied'),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='old_value',
            field=models.TextField(blank=True, help_text='Previous value (for audit)'),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingprofilechange',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_confirmation_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_confirmation_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email address awaiting confirmation', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requires_reconfirmation',
            field=models.BooleanField(default=False, help_text='Requires email re-confirmation due to security changes'),
        ),
        migrations.AddIndex(
            model_name='pendingprofilechange',
            index=models.Index(fields=['token'], name='council_fin_token_32b1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingprofilechange',
            index=models.Index(fields=['user', 'status'], name='council_fin_user_id_5a6e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingprofilechange',
            index=models.Index(fields=['expires_at'], name='council_fin_expires_d5c4d8_idx'),
        ),
    ]
