# Generated by Django 5.2.3 on 2025-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0061_add_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingprofilechange',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
