# Generated by Django 5.2.3 on 2025-07-24 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('council_finance', '0063_alter_factoidplaylist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoidTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this template', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('template_text', models.TextField(help_text='Template with {field} placeholders. Supports :currency, :percentage, :number formatters')),
                ('factoid_type', models.CharField(choices=[('context', '📋 Contextual Information'), ('comparison', '⚖️ Peer Comparison'), ('trend', '📈 Multi-Year Trend'), ('ranking', '🏆 Council Ranking'), ('per_capita', '👤 Per Capita Analysis'), ('ratio', '🔢 Financial Ratio'), ('milestone', '🎯 Milestone Achievement'), ('sustainability', '🌱 Financial Health'), ('percent_change', '📊 Percentage Change'), ('anomaly', '⚠️ Data Anomaly')], default='context', max_length=20)),
                ('emoji', models.CharField(blank=True, help_text='Primary emoji for this factoid', max_length=10)),
                ('color_scheme', models.CharField(choices=[('green', '🟢 Positive (Green)'), ('red', '🔴 Negative (Red)'), ('blue', '🔵 Neutral (Blue)'), ('orange', '🟠 Warning (Orange)'), ('purple', '🟣 Special (Purple)')], default='blue', max_length=20)),
                ('priority', models.IntegerField(default=50, help_text='Higher priority shows first (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requires_previous_year', models.BooleanField(default=False)),
                ('animation_duration', models.PositiveIntegerField(default=5000, help_text='Display duration in milliseconds')),
                ('flip_animation', models.BooleanField(default=True, help_text='Enable flip animation')),
                ('referenced_fields', models.JSONField(default=list, help_text='Auto-populated list of field names referenced in template')),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council_types', models.ManyToManyField(blank=True, help_text='Limit to specific council types', to='council_finance.counciltype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_factoid_templates', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, help_text='What type of data this factoid applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Factoid Template',
                'verbose_name_plural': 'Factoid Templates',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FactoidInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_text', models.TextField()),
                ('computed_data', models.JSONField(default=dict, help_text='Source data used for rendering')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Computed relevance score (0.0-1.0)')),
                ('is_significant', models.BooleanField(default=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.council')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council_finance.counterdefinition')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.financialyear')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.factoidtemplate')),
            ],
            options={
                'verbose_name': 'Factoid Instance',
                'verbose_name_plural': 'Factoid Instances',
                'ordering': ['-relevance_score', '-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoidFieldDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True, help_text='If true, changes to this field invalidate all instances')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.datafield')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council_finance.factoidtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='factoidtemplate',
            index=models.Index(fields=['factoid_type', 'is_active'], name='council_fin_factoid_28929f_idx'),
        ),
        migrations.AddIndex(
            model_name='factoidtemplate',
            index=models.Index(fields=['priority', '-created_at'], name='council_fin_priorit_f3ca8f_idx'),
        ),
        migrations.AddIndex(
            model_name='factoidinstance',
            index=models.Index(fields=['council', 'financial_year'], name='council_fin_council_7d45d7_idx'),
        ),
        migrations.AddIndex(
            model_name='factoidinstance',
            index=models.Index(fields=['template', 'is_significant'], name='council_fin_templat_00b137_idx'),
        ),
        migrations.AddIndex(
            model_name='factoidinstance',
            index=models.Index(fields=['relevance_score', '-computed_at'], name='council_fin_relevan_8f8d94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factoidinstance',
            unique_together={('template', 'council', 'financial_year', 'counter')},
        ),
        migrations.AddIndex(
            model_name='factoidfielddependency',
            index=models.Index(fields=['field', 'is_critical'], name='council_fin_field_i_a69f03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factoidfielddependency',
            unique_together={('template', 'field')},
        ),
    ]
