# Generated by Django 5.2.3 on 2025-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0064_add_enhanced_factoid_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoidtemplate',
            name='counters',
            field=models.ManyToManyField(blank=True, help_text='Counters this factoid can provide insights for', related_name='factoid_templates', to='council_finance.counterdefinition'),
        ),
    ]
