# Generated by Django 5.2.3 on 2025-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0065_factoidtemplate_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='content_type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('integer', 'Integer'), ('text', 'Text'), ('url', 'URL'), ('postcode', 'Post Code'), ('phone', 'Phone Number'), ('latlong', 'Latitude/Longitude'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('boolean', 'True/False'), ('list', 'List')], default='text', max_length=20),
        ),
    ]
