# Generated by Django 5.2.3 on 2025-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0068_add_image_file_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafield',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='datafield',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which to display this field in the council meta bar (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='icon_svg_path',
            field=models.CharField(blank=True, help_text="Heroicon SVG path for display in council meta bar (e.g., 'M17 20h5v-2a3...')", max_length=255),
        ),
        migrations.AddField(
            model_name='datafield',
            name='meta_display_format',
            field=models.CharField(blank=True, default='{value}', help_text="Format string for displaying value in meta bar. Use {value} as placeholder (e.g., '{value} residents')", max_length=100),
        ),
        migrations.AddField(
            model_name='datafield',
            name='show_in_meta',
            field=models.BooleanField(default=False, help_text='Whether to show this field in the council detail meta bar'),
        ),
    ]
