# Generated by Django 5.2.3 on 2025-07-29 20:01

from django.db import migrations


def populate_meta_defaults(apps, schema_editor):
    """Set default meta display options for common characteristic fields."""
    DataField = apps.get_model('council_finance', 'DataField')
    
    # Define default settings for common fields
    field_defaults = {
        'council-type': {
            'show_in_meta': True,
            'display_order': 10,
            'icon_svg_path': 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4',
            'meta_display_format': '{value}'
        },
        'council-nation': {
            'show_in_meta': True,
            'display_order': 20,
            'icon_svg_path': 'M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z M15 11a3 3 0 11-6 0 3 3 0 016 0z',
            'meta_display_format': '{value}'
        },
        'population': {
            'show_in_meta': True,
            'display_order': 30,
            'icon_svg_path': 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
            'meta_display_format': '{value} residents'
        },
        'households': {
            'show_in_meta': True,
            'display_order': 40,
            'icon_svg_path': 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6',
            'meta_display_format': '{value} households'
        },
        'council-website': {
            'show_in_meta': True,
            'display_order': 50,
            'icon_svg_path': 'M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14',
            'meta_display_format': '{value}'
        },
        'elected-members': {
            'show_in_meta': False,
            'display_order': 60,
            'icon_svg_path': 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z',
            'meta_display_format': '{value} councillors'
        }
    }
    
    # Apply updates
    for slug, settings in field_defaults.items():
        try:
            field = DataField.objects.get(slug=slug)
            for key, value in settings.items():
                setattr(field, key, value)
            field.save()
        except DataField.DoesNotExist:
            pass  # Field doesn't exist yet, skip


def reverse_meta_defaults(apps, schema_editor):
    """Reverse the meta defaults."""
    DataField = apps.get_model('council_finance', 'DataField')
    
    # Reset all fields to defaults
    DataField.objects.update(
        show_in_meta=False,
        display_order=0,
        icon_svg_path='',
        meta_display_format='{value}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0069_add_field_meta_display_options'),
    ]

    operations = [
        migrations.RunPython(populate_meta_defaults, reverse_meta_defaults),
    ]
