# Generated by Django 5.2.3 on 2025-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0070_populate_field_meta_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='icon_svg_path',
            field=models.TextField(blank=True, help_text="Heroicon SVG path for display in council meta bar (e.g., 'M17 20h5v-2a3...')"),
        ),
    ]
