# Generated by Django 5.2.3 on 2025-07-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0071_fix_icon_svg_path_field_type'),
    ]

    operations = [
        # Index for meta fields lookup optimization
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_datafield_meta_display ON council_finance_datafield(show_in_meta, category, display_order) WHERE show_in_meta = true;",
            reverse_sql="DROP INDEX IF EXISTS idx_datafield_meta_display;"
        ),
        
        # Index for counter definition filtering by council type
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_counter_council_types ON council_finance_counterdefinition_council_types(counterdefinition_id, counciltype_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_counter_council_types;"
        ),
        
        # Index for DataField slug lookups (used frequently in CounterAgent)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_datafield_slug_content_type ON council_finance_datafield(slug, content_type) WHERE content_type IN ('monetary', 'integer');",
            reverse_sql="DROP INDEX IF EXISTS idx_datafield_slug_content_type;"
        ),
    ]
