# Generated by Django 5.2.3 on 2025-07-30 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0072_add_counter_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councillist',
            options={'ordering': ['-is_default', '-updated', 'name']},
        ),
        migrations.AddField(
            model_name='councillist',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('indigo', 'Indigo'), ('pink', 'Pink'), ('gray', 'Gray')], default='blue', help_text='Color theme for this list', max_length=20),
        ),
        migrations.AddField(
            model_name='councillist',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about this list', null=True),
        ),
        migrations.AddField(
            model_name='councillist',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Whether this is the user's default favourites list"),
        ),
        migrations.AddField(
            model_name='councillist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='councillist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_list_per_user'),
        ),
    ]
