# Generated by Django 5.2.3 on 2025-07-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0073_enhance_council_list_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='url_allow_redirects',
            field=models.BooleanField(default=True, help_text='Allow URLs that redirect to other locations'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='url_allowed_domains',
            field=models.TextField(blank=True, help_text='If specified, only allow URLs from these comma-separated domains'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='url_blocked_domains',
            field=models.TextField(blank=True, help_text="Comma-separated list of domains to block (e.g., 'example.com,malicious.site')"),
        ),
        migrations.AddField(
            model_name='datafield',
            name='url_require_https',
            field=models.BooleanField(default=False, help_text='Require HTTPS protocol for URL fields'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='url_validation_enabled',
            field=models.BooleanField(default=True, help_text='Whether to perform security validation on URL fields'),
        ),
    ]
