# Generated by Django 5.2.3 on 2025-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0074_add_url_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialfigure',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
