# Generated by Django 5.2.3 on 2025-08-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0076_add_activity_log_comments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylogcomment',
            new_name='council_fin_activit_6c65d6_idx',
            old_name='council_fin_activit_4c8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylogcomment',
            new_name='council_fin_user_id_9b95d5_idx',
            old_name='council_fin_user_id_b8c726_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylogcomment',
            new_name='council_fin_parent__4e96bb_idx',
            old_name='council_fin_parent__6c0421_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylogcomment',
            new_name='council_fin_is_flag_a5344d_idx',
            old_name='council_fin_is_flag_e31c5b_idx',
        ),
    ]
