# Generated by Django 5.2.3 on 2025-08-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0077_rename_council_fin_activit_4c8b9c_idx_council_fin_activit_6c65d6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
