# Generated by Django 5.2.3 on 2025-08-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0081_predictive_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilnation',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=100, unique=False),
        ),
    ]
