# Generated by Django 5.2.3 on 2025-08-04 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0084_make_council_nation_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilnation',
            name='capital_city',
            field=models.CharField(blank=True, help_text='Administrative center/capital city', max_length=100),
        ),
        migrations.AddField(
            model_name='councilnation',
            name='council_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of local authorities in this nation', null=True),
        ),
        migrations.AddField(
            model_name='councilnation',
            name='currency_code',
            field=models.CharField(default='GBP', help_text='ISO currency code (GBP for UK nations)', max_length=3),
        ),
        migrations.AddField(
            model_name='councilnation',
            name='display_colour',
            field=models.CharField(blank=True, default='#1d70b8', help_text='Hex color code for charts and data visualization (e.g. #1d70b8)', max_length=7),
        ),
        migrations.AddField(
            model_name='councilnation',
            name='total_area_km2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total geographic area in square kilometres', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='councilnation',
            name='total_population',
            field=models.PositiveIntegerField(blank=True, help_text='Total population of this nation (for nation-level per capita calculations)', null=True),
        ),
    ]
