# Generated by Django 5.2.3 on 2025-08-04 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0086_populate_council_nation_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counciltype',
            options={'ordering': ['tier_level', 'name'], 'verbose_name': 'Council type', 'verbose_name_plural': 'Council types'},
        ),
        migrations.AddField(
            model_name='counciltype',
            name='council_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of councils of this type in the UK', null=True),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed explanation of what this council type does and its responsibilities'),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='display_colour',
            field=models.CharField(blank=True, default='#1d70b8', help_text='Hex color code for charts and data visualization (e.g. #1d70b8)', max_length=7),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this council type is currently in use (allows disabling without deleting)'),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=100, unique=False),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='tier_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tier level: 1=Unitary, 2=Upper Tier (County), 3=Lower Tier (District), 4=Parish, 5=Other', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='counciltype',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Link to Wikipedia or other educational resource about this council type'),
        ),
    ]
