# Generated by Django 5.2.3 on 2025-08-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0090_siteannouncement_sitefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefeedback',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='Screen resolution when issue occurred', max_length=50),
        ),
    ]
