# Generated by Django 5.2.3 on 2025-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0091_increase_screen_resolution_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth0_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Auth0 user metadata'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth0_user_id',
            field=models.CharField(blank=True, help_text='Auth0 user identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_method',
            field=models.CharField(blank=True, help_text='Last authentication method used', max_length=50),
        ),
    ]
