# Generated by Django 5.2.3 on 2025-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0092_userprofile_auth0_metadata_userprofile_auth0_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_verified',
            field=models.BooleanField(default=False, help_text='User has completed age verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_comments',
            field=models.BooleanField(default=True, help_text='User can access comments and feed sections'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community_guidelines_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted community guidelines'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community_guidelines_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When guidelines were accepted', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required for Online Safety Act compliance', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_uk_user',
            field=models.BooleanField(default=True, help_text='User is based in the United Kingdom'),
        ),
    ]
