# Generated by Django 5.2.3 on 2025-08-15 06:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_finance', '0095_add_pdf_document_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreFinancialFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, help_text='Total income for the financial year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('council_tax_income', models.DecimalField(blank=True, decimal_places=2, help_text='Income from council tax collection', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('business_rates_income', models.DecimalField(blank=True, decimal_places=2, help_text='Income from business rates (NNDR)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('government_grants_income', models.DecimalField(blank=True, decimal_places=2, help_text='Government grants and specific grants', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fees_and_charges_income', models.DecimalField(blank=True, decimal_places=2, help_text='Income from fees and charges for services', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, help_text='Total expenditure for the financial year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('employee_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Staff costs including salaries, pensions, NI', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('premises_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Buildings, maintenance, utilities, business rates', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Vehicle costs, fuel, public transport contracts', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('supplies_and_services', models.DecimalField(blank=True, decimal_places=2, help_text='Equipment, supplies, professional services', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Cash, short-term investments, debtors', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('long_term_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Property, plant, equipment, long-term investments', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Total of current and long-term assets', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('property_plant_equipment', models.DecimalField(blank=True, decimal_places=2, help_text='Property, plant and equipment at net book value', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Short-term debts due within one year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('long_term_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Long-term debts due after one year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pension_liability', models.DecimalField(blank=True, decimal_places=2, help_text='Pension fund deficit (can be negative for surplus)', max_digits=15, null=True)),
                ('finance_leases', models.DecimalField(blank=True, decimal_places=2, help_text='Finance lease obligations and PFI liabilities', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('provisions', models.DecimalField(blank=True, decimal_places=2, help_text='Provisions for future liabilities', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, help_text='Total outstanding debt (often calculated field)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_payments', models.DecimalField(blank=True, decimal_places=2, help_text='Interest paid on borrowings during the year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('borrowing_costs', models.DecimalField(blank=True, decimal_places=2, help_text='Total borrowing costs including interest and fees', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_reserves', models.DecimalField(blank=True, decimal_places=2, help_text='Total reserves (can be negative for deficit)', max_digits=15, null=True)),
                ('usable_reserves', models.DecimalField(blank=True, decimal_places=2, help_text='Reserves available to fund future expenditure', max_digits=15, null=True)),
                ('unusable_reserves', models.DecimalField(blank=True, decimal_places=2, help_text='Reserves not available for spending (revaluation, etc.)', max_digits=15, null=True)),
                ('general_fund_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Unallocated general fund balance', max_digits=15, null=True)),
                ('capital_expenditure', models.DecimalField(blank=True, decimal_places=2, help_text='Capital expenditure on assets during the year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capital_receipts', models.DecimalField(blank=True, decimal_places=2, help_text='Income from sale of capital assets', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capital_grants', models.DecimalField(blank=True, decimal_places=2, help_text='Capital grants received during the year', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('pdf_import', 'PDF Import'), ('csv_import', 'CSV Import'), ('api_import', 'API Import'), ('migration', 'Data Migration')], default='manual', help_text='How this data was entered into the system', max_length=50)),
                ('source_file_name', models.CharField(blank=True, help_text='Name of imported file (if applicable)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_figures', to='council_finance.council')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_figures', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_core_figures', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_figures', to='council_finance.financialyear')),
            ],
            options={
                'verbose_name': 'Core Financial Figure',
                'verbose_name_plural': 'Core Financial Figures',
                'indexes': [models.Index(fields=['council', 'year'], name='council_fin_council_e14f10_idx'), models.Index(fields=['council'], name='council_fin_council_df6677_idx'), models.Index(fields=['year'], name='council_fin_year_id_fabbbf_idx'), models.Index(fields=['data_source'], name='council_fin_data_so_ee4d88_idx'), models.Index(fields=['updated_at'], name='council_fin_updated_8ada18_idx')],
                'unique_together': {('council', 'year')},
            },
        ),
    ]
