from .general import (
    my_lists,
    following as following_view,
    follow_item_api,
    unfollow_item_api,
    interact_with_update_api,
    comment_on_update_api,
    update_feed_preferences_api,
    get_feed_updates_api,
    add_favourite,
    remove_favourite,
    add_to_list,
    remove_from_list,
    move_between_lists,
    list_metric,
    add_to_compare,
    remove_from_compare,
    compare_row,
    compare_basket,
    clear_compare_basket,
    follow_council,
    unfollow_council,
    like_update,
    comment_update,
)

# Create an alias for the following view to avoid namespace collision
following = following_view

__all__ = [
    'my_lists',
    'following',
    'follow_item_api',
    'unfollow_item_api',
    'interact_with_update_api',
    'comment_on_update_api',
    'update_feed_preferences_api',
    'get_feed_updates_api',
    'add_favourite',
    'remove_favourite',
    'add_to_list',
    'remove_from_list',
    'move_between_lists',
    'list_metric',
    'add_to_compare',
    'remove_from_compare',
    'compare_row',
    'compare_basket',
    'clear_compare_basket',
    'follow_council',
    'unfollow_council',
    'like_update',
    'comment_update',
]
